//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manuu
{
    using System;
    using System.Collections.Generic;
    // класс Bludo, который представляет информацию о блюде
    public partial class Bludo
    {
        public int id_bludo { get; set; }
        public string name_bludo { get; set; }
        public int ves_porc { get; set; }
        public int kalariynost { get; set; }
        public int price { get; set; }
    }
}
