//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manuu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class for_restoranEntities : DbContext
    {
        private static for_restoranEntities _context;

        public static for_restoranEntities GetContext()
        {
            if (_context == null)
                _context = new for_restoranEntities();
            return _context;
        }
        public for_restoranEntities()
            : base("name=for_restoranEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bludo> Bludo { get; set; }
        public virtual DbSet<Dolj> Dolj { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Receptura> Receptura { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
