//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manuu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id_product { get; set; }
        public string name_product { get; set; }
        public string units_of_measurement { get; set; }
    }
}
