//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manuu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receptura
    {
        public int id_recepture { get; set; }
        public int id_bludo { get; set; }
        public int id_product { get; set; }
        public int kolichestvo { get; set; }
        public string sposob_obrab { get; set; }
    }
}
